name: CICD

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build image
        run: docker build --tag subugoe/hoad:${{ github.sha }} .
      - name: Upload image
        uses: actions/upload-artifact@v1
        with:
          name: hoad
          path: /var/lib/docker
  Check:
    runs-on: ubuntu-18.04
    needs: build
    container:
      image: subugoe/hoad:${{ github.sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Download image
        uses: actions/download-artifact@v1
        with:
          name: hoad
          path: /var/lib/docker
      - run: ls /var/lib/docker
      - name: Check Package
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
      - name: Run Code Coverage
        run: Rscript -e "covr::codecov(quiet = FALSE, commit = '$GITHUB_SHA', branch = '$GITHUB_REF', token = '${{ secrets.CODECOV_TOKEN }}')"
