name: CICD

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build image
        run: docker build --tag docker.pkg.github.com/subugoe/hybrid_oa_dashboard/hoad:${{ github.sha }} .
      - name: Login
        run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Push image
        run: docker push docker.pkg.github.com/subugoe/hybrid_oa_dashboard/hoad:${{ github.sha }}
  Check:
    runs-on: ubuntu-18.04
    needs: build
    container:
      image: docker.pkg.github.com/subugoe/hybrid_oa_dashboard/hoad:${{ github.sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Check Package
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
      - name: Run Code Coverage
        run: Rscript -e "covr::codecov(quiet = FALSE, commit = '$GITHUB_SHA', branch = '$GITHUB_REF', token = '${{ secrets.CODECOV_TOKEN }}')"
