name: CICD

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build image
        run: docker build --tag hoad .
      - name: Tag image
        run: |
          docker tag hoad docker.pkg.github.com/subugoe/hybrid_oa_dashboard/hoad:${{ github.sha }}
          docker tag hoad maxheld83/hoad:${{ github.sha }}
      - name: Push image to github package registry
        run: |
          docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          docker push docker.pkg.github.com/subugoe/hybrid_oa_dashboard/hoad:${{ github.sha }}
      - name: Push image to docker hub
        run: |
          docker login -u maxheld83 -p ${{ secrets.DOCKER_TOKEN }}
          docker push maxheld83/hoad:${{ github.sha }}
  Check:
    runs-on: ubuntu-18.04
    needs: build
    container:
      image: maxheld83/hoad:${{ github.sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: R CMD Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: check
      - name: Run Code Coverage
        run: covr::codecov(quiet = FALSE, commit = '$GITHUB_SHA', branch = '$GITHUB_REF', token = '${{ secrets.CODECOV_TOKEN }}')
        shell: Rscript {0}
