on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, created, edited]

jobs:
  cicd:
    # below until steps needs to be the same in dockerfile
    runs-on: ubuntu-18.04
    env:
      # this freezes the package versions
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/bionic/279"
      # unfortunately this has to be updated by hand
      LIB_PATH: "/opt/R/4.0.0/lib/R/library"
    container:
      # this freezes the r version
      image: "rstudio/r-base:4.0-bionic"
    steps:
      - uses: actions/checkout@v2
      - name: Query dependencies
        run: |
          options(warn = 2)
          install.packages('remotes', repos = Sys.getenv('RSPM'))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = Sys.getenv("RSPM")), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.LIB_PATH }}
          key: ${{ env.RSPM }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.RSPM }}-
      - name: Install System dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          # stupid hack to fix https://github.com/r-hub/sysreqsdb/issues/77
          apt update && apt install -y software-properties-common
          add-apt-repository ppa:cran/libgit2
          Rscript -e "remotes::install_github('r-hub/sysreqs', ref='3860f2b512a9c3bd3db6791c2ff467a1158f4048')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install Package Dependencies
        run: |-
          remotes::install_deps(dependencies = TRUE, repos = Sys.getenv('RSPM'))
        shell: Rscript {0}
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
      - name: Copy dependencies to working directory
        run: |
          cp --recursive --force ${{ env.LIB_PATH }}/* deps/
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: subugoe/hoad
          tag_with_sha: true
          tag_with_ref: true
          add_git_labels: true
          tags: ${{ github.sha }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Build Package Website
        run: |
          pkgdown::build_site(override = list(new_process = FALSE))
        shell: Rscript {0}
#      - name: Deploy Shiny Application to shinyapps.io ref
#        if: github.event_name != 'pull_request'
#        run: |
#          Rscript -e "rsconnect::setAccountInfo(name = 'subugoe', token = Sys.getenv('SHINYAPPS_TOKEN'), secret = Sys.getenv('SHINYAPPS_SECRET'))"
#          Rscript -e "rsconnect::deployApp(appName = paste0('hoad-', Sys.getenv('GITHUB_REF')))"
#        env:
#          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
#          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
#          GITHUB_REF: ${{ github.ref }}
      - name: Get system dependencies for github pages deploy
        run: apt-get update -y && apt-get install -y ssh rsync
      - name: Deploy pkgdown website to ref
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          TARGET_FOLDER: ${{ github.ref }}
      - name: Deploy pkgdown website to root
        if: github.event_name == 'release'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
