name: CICD

on:
  - push
  - pull_request

jobs:
  build_image:
    runs-on: ubuntu-18.04
    name: Build and Push Container
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: subugoe/hoad
          tag_with_sha: true
          tag_with_ref: true
          add_git_labels: true
          tags: ${{ github.sha }}
  check:
    runs-on: ubuntu-18.04
    needs: build_image
    container:
      image: subugoe/hoad:${{ github.sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: R CMD Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: check
      - name: Run Code Coverage
        run: covr::codecov(commit = '$GITHUB_SHA', branch = '$GITHUB_REF', token = '${{ secrets.CODECOV_TOKEN }}')
        shell: Rscript {0}
