on:
  - push
  - pull_request

name: r-hub

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    container:
      image: rhub/${{ matrix.config.container }}

    name: ${{ matrix.config.os }} (${{ matrix.config.container }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: ubuntu-16.04,
              container: "ubuntu-gcc-release",
              cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest",
            }
          - {
              os: ubuntu-16.04,
              container: "ubuntu-gcc-release",
              cran: "https://cran.rstudio.com/",
            }

    env:
      CRAN: ${{ matrix.config.cran }}
    steps:
      - uses: actions/checkout@v2

      - name: Query dependencies
        run: |
          options(warn = 2)
          install.packages('remotes', repos = Sys.getenv("CRAN"))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      # - name: Cache R packages
      #   uses: actions/cache@v1
      #   with:
      #     path: /usr/local/lib/R/site-library
      #     key: ${{ runner.os }}-${{ matrix.config.container }}-${{ hashFiles('depends.Rds') }}
      #     restore-keys: ${{ runner.os }}-r-${{ matrix.config.container }}-

      - name: Install system dependencies
        if: runner.os != 'Windows'
        run: |
          Rscript -e "options(warn = 2); remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          eval "$sysreqs"

      - name: Install dependencies
        run: |
          options(warn = 2)
          remotes::install_deps(dependencies = TRUE, repos = Sys.getenv("CRAN"))
          remotes::install_cran("rcmdcheck", repos = Sys.getenv("CRAN"))
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.container }}-results
          path: check
